### ISSUE TITLE
Custom integration rules classpath configuration is not working.

### ISSUE THREAD

**Issue by jianshaow** [opentracing-contrib/java-specialagent#537] opened 2020-04-08 10:56 UTC
As document mention that custom integration rules should be loaded via `-Dsa.classpath=${JARs}`, but the config doesn't work. Dig in code, the effective config is `-Dsa.include`. One of them should be wrong, in code or doc.

**Comment by safris** [comment] 2020-04-08 12:16
Thank you for catching this @jianshaow. You are correct, there is a discrepancy between the docs and the code. I've updated the code to use: `-Dsa.classpath=${JARs}`.

**Comment by safris** [comment] 2020-04-14 02:15
Hi @jianshaow, I'm going to close this issue. If the problem is not resolved, please feel free to reopen.

**Closed by safris** 2020-04-14 02:15 UTC
Labels: P2, bug, core
