### ISSUE TITLE
NoClassDefFoundError with Servlet Filter causes application to fail

### ISSUE THREAD

**Issue by pc-alves** [opentracing-contrib/java-specialagent#308] opened 2019-12-14 17:45 UTC
Hi!

I am trying to use the specialagent to instrument a legacy application. While some of the plugins are working, the javax servlet one is causing the application to fail.

This is the error being thrown in the application:

```
PluginManifest.get(/var/folders/3g/sk2hj63d485cxd72d4lt4088dz68_2/T/opentracing-specialagent38983911031602862/META-INF/plugins/servlet-1.5.3-SNAPSHOT.jar </var/folders/3g/sk2hj63d485cxd72d4lt4088dz68_2/T/opentracing-specialagent38983911031602862/META-INF/plugins/servlet-1.5.3-SNAPSHOT.jar>): PluginManifest@4d6aae69
SpecialAgent#linkRule("servlet"[4], org.codehaus.plexus.classworlds.realm.ClassRealm@28344389): compatible = true [cached]
PluginManifest.get(/var/folders/3g/sk2hj63d485cxd72d4lt4088dz68_2/T/opentracing-specialagent38983911031602862/META-INF/plugins/servlet-1.5.3-SNAPSHOT.jar </var/folders/3g/sk2hj63d485cxd72d4lt4088dz68_2/T/opentracing-specialagent38983911031602862/META-INF/plugins/servlet-1.5.3-SNAPSHOT.jar>): PluginManifest@4d6aae69
SpecialAgent#linkRule("servlet"[4], org.codehaus.plexus.classworlds.realm.ClassRealm@28344389): compatible = true [cached]
Dec 14, 2019 5:27:59 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [default] in context with path [] threw exception [Filter execution threw an exception] with root cause
java.lang.ClassNotFoundException: io.opentracing.contrib.specialagent.rule.servlet.ServletContextAgentRule
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1713)
	at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1558)
	at <proprietary filter>
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

-------> Intercept from: public void org.apache.catalina.connector.Response.setStatus(int)
-------> Intercept from: public void org.apache.catalina.connector.Response.setStatus(int)
Dec 14, 2019 5:27:59 PM org.apache.coyote.http11.AbstractHttp11Processor process
SEVERE: Error processing request
java.lang.NoClassDefFoundError: io/opentracing/contrib/specialagent/rule/servlet/FilterAgentIntercept
	at org.apache.catalina.connector.Response.setStatus(Response.java:1488)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:424)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:179)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Some details of the project setup:

Maven Version:
- Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 14:51:28+0100)

Java Version:
- 1.7.0_80, vendor: Oracle Corporation

Servlet Version:
- javax.servlet:servlet-api:jar:2.5:provided

Tomcat Version:

- org.apache.tomcat:tomcat-coyote:jar:7.0.56:provided
- org.apache.tomcat:tomcat-servlet-api:jar:7.0.56:provided
- org.apache.tomcat:tomcat-api:jar:7.0.56:provided

I noticed that the tomcat dependencies were for a version older than the one listed in the specialagent documentation, so I tried to add 7.0.56 in the servlet rule's tests, and built a custom agent. The tests passed. The application, however, is still failing.

Attached is the file with the references to the servlet plugin that I identified in the agent startup: 
[servlet-references.log](https://github.com/opentracing-contrib/java-specialagent/files/3964118/servlet-references.log)

In the logs above I see that the rule is loaded, and the class is added to the Class Loaders, which just adds to the confusion as to why the class is not found.

Let me know if there is any other information that I could add to help troubleshoot this.
Any hints that would allow me to figure out what is the problem would be greatly appreciated.

Thanks in advance.

**Comment by safris** [comment] 2019-12-16 17:31
Hi @pc-alves, thanks for reporting this issue. Are you able to provide a test project that can demonstrate this error?

**Comment by pc-alves** [comment] 2019-12-19 08:28
@safris Apologies for the delay, and thank you for looking into this.

Right now the confidence that building a test project would be representative of the complexity of the existing (monolithical) application, and all its intricacies, is low. But it's still an option to consider.

However, in the mean time further experiments haven taken place, and here is what we have found out, so far:

- We added logging to the catch block in [RuleClassLoader.java#64](https://github.com/opentracing-contrib/java-specialagent/blob/master/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/RuleClassLoader.java#L64), and found that the classes for servlet instrumentation (and others) are all returning `ClassNotFoundException`, matching the behaviour in the application. See [specialagent-with-extra-errors.log](https://github.com/opentracing-contrib/java-specialagent/files/3979214/specialagent-with-extra-errors.log)
- In my original comment I mentioned that I was able to run the application and the agent, with servlet plugin disabled, and spans were created and exported. I recreated this just to confirm the versions that I achieved it with. This was with Java8 and specialagent 1.5.0. After that I tried with version 1.5.1 and 1.5.3 (the one from the logs above), and I get the same error with other plugins.

Given that we also see `ClassNotFoundException`s during the agent startup, we are looking into explicitly adding the agent jars to tomcat's class path.
Further experiments will also be using specialagent 1.5.0, as this seems to be the one that still manages to have something working.
Finally, one thing that may be worth mentioning, is that we are doing dynamic attach. However, the commands documented in the README only mention Java8 and above. Is there a difference to this command when running with Java7?

Let me know if the experiments above give any hint to what could be the issue. I'll share more infromation as we go along. Thank you.

**Comment by safris** [comment] 2019-12-19 10:16
Hi @pc-alves, thanks for the follow-up. There's a lot going on here, so let me itemize my responses:
1. You do not need to add logging to the catch block in [RuleClassLoader.java#64](https://github.com/opentracing-contrib/java-specialagent/blob/master/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/RuleClassLoader.java#L64). The exceptions occurring in this block are coming from [SpecialAgentAgent.java#89-114](https://github.com/opentracing-contrib/java-specialagent/blob/master/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/SpecialAgentAgent.java#L89-L114). By turning on `-Dsa.log.level=FINEST`, you will see all of the same exceptions logged. It is these logs that are designed to help identify the problem, so I encourage you to revert your code and turn logging to `FINEST` instead.
1. I am not clear what you are saying with regard to v1.5.0 vs v1.5.3. There have not been any changes to the SpecialAgent's class loading core between versions v1.5.0 and v1.5.3. If you had "some success" with v1.5.0 but not v1.5.3, this unfortunately is not narrow enough of a scope of conditions for me to use as the starting point of identifying why you don't have similar amount of "some success" with later versions.
1. I recommend you use the latest version of SpecialAgent (1.5.4-SNAPSHOT), simply because this will greatly reduce the time I would need in identifying the issue. If you do find that something is working in v1.5.0, but not in v1.5.3, it would significantly multiply the amount of time I would need in bridging to the latest version.
1. If the dynamic attach command itself is not throwing an exception, then it's working!
1. Please **do not add the SpecialAgent JAR to the classpath**. Doing so will cause many other problems, and will not lead you forward. The SpecialAgent JAR is intended to _only_ be used with the `-javaagent` argument, or via Dynamic Attach.
1. If I cannot reproduce the problem, there is very little chance that I would be able to deduce what could be happening with the limited information. SpecialAgent is not tested with jdk1.7, so it may be possible that a simple demo of your use-case run with jdk1.7 would surface the issue.

The SpecialAgent in general, and the `servlet` plugin in specific, are very complex. I would be eager to help, but please help me help you by making this problem accessible for me to investigate.

**Comment by pc-alves** [comment] 2019-12-23 14:42
Thank you for the hints, @safris 

Regarding 2., here are further details of the experiment, and the observations:

- Java 1.8; Specialagent 1.5.0; Servlet plugin disabled; Application works and creates spans.
- Java 1.8; Specialagent 1.5.0; Servlet plugin enabled; Application fails with `ClassNotFoundException` trying to find `io.opentracing.contrib.specialagent.rule.servlet.FilterAgentIntercept`
- Java 1.7; custom Specialagent 1.5.0 (backported to Java7); same behavior as with Java 1.8
- Java 1.7; Specialagent 1.5.3; Servlet plugin enabled; Application fails with `ClassNotFoundException` trying to find `io.opentracing.contrib.specialagent.rule.servlet.FilterAgentIntercept`
- Java 1.7; Specialagent 1.5.3; Servlet plugin disabled; Application fails with `ClassNotFoundException` for the Jedis plugin. 

We're work on creating a demo app that can reproduce the errors we're getting, and come back to you as soon as there is something in working order. So far we haven't been able to reproduce the error.

**Comment by safris** [comment] 2020-01-06 09:52
Hi @pc-alves, I wanted to check if you have had any luck creating a demo app to reproduce the error you're seeing. I have added Jetty 9.3.28 and 9.4.24 to the versions that are regression tested by the SpecialAgent build. Since our tests pass, you have a use-case that is outside the scope of our test cases.

**Comment by pc-alves** [comment] 2020-01-07 09:05
Hi @safris. Things went a bit slow over the holidays. However, we did create a small app to try to replicate the issue. While doing so, we noticed that the errors I reported were only obtained while running the maven version that the legacy project requires (3.0.5). When we run it with maven 3.6.3 everything works fine.

As we don't actually need maven to run the app (we just deploy it to tomcat in production), we are now running tests by deploying the application to tomcat locally to confirm our assumptions. For one, we now see the servlet spans with Java 1.8, which is an improvement from our starting point. Will keep you up to date on our latest findings.

**Comment by zeitlinger** [comment] 2020-01-09 10:59
Hi @safris - I worked with @pc-alves on this topic.

Our test with tomcat was successful - also with Java 1.7.

We did find a couple of issues along the say - and I'll open separate issues for them, to keep the discussion more focused.

This issue can be closed now.

**Comment by safris** [comment] 2020-01-09 13:26
Thank you for the update @zeitlinger. I will close this issue, and will look out for your subsequent issues.

**Closed by safris** 2020-01-09 13:26 UTC
Labels: bug
