### ISSUE TITLE
SpecialAgent for WAS - No Output/Logs

### ISSUE THREAD

**Issue by haf-tech** [opentracing-contrib/java-specialagent#294] opened 2019-12-08 20:30 UTC
I am trying to use the SpecialAgent with an WebSphere Application Server instance.
I have the following script to start the SpecialAgent and use dynamic attachment.

```
#!/bin/sh

java -Xbootclasspath/a:$JAVA_HOME/lib/tools.jar \
 -Dsa.log.level=FINEST \
 -Dsa.log.events=COMPLETE \
 -Dsa.log.file=b.log \
 -Dsa.instrumentation.plugin.verbose=true \
 -Dsa.fingerprint.skip=true \
 -Dsa.tracer=jaeger -DJAEGER_AGENT_HOST="http://127.0.0.1" \
 -DJAEGER_AGENT_PORT=5775 \
 -DJAEGER_REPORTER_LOG_SPANS=true \
 -DJAEGER_SAMPLER_TYPE=const \
 -DJAEGER_SAMPLER_PARAM=1 \
 -DJAEGER_SERVICE_NAME=my-app \
 -jar opentracing-specialagent-1.5.2.jar $1
```

But I do not see any error messages and the log file "b.log" is empty.
I execute the SpecialAgent with the same user, as the target VM is running.

In case if I pass a "wrong" PID I see a corresponding error message.

So, how to get any details? Any hints?
Thanks in advance

**Comment by safris** [comment] 2019-12-09 11:31
Hi @haf-tech, thank you for bringing our attention to this issue. I have committed a change to attempts to fix this problem. When [this build](https://travis-ci.org/opentracing-contrib/java-specialagent/builds/622612405) completes, please [download the development build](https://github.com/opentracing-contrib/java-specialagent/#2112-development) and try your test again.

**Comment by haf-tech** [comment] 2019-12-09 14:37
tested with
`opentracing-specialagent-1.5.3-20191209.130556-16.jar | Mon Dec 09 13:08:54 UTC 2019 | 21616604`
with the same result. 
Log file is still empty. No other output.

**Comment by safris** [comment] 2019-12-09 14:41
Hi @haf-tech, I unfortunately cannot reproduce your issue. When I specify the `-Dsa.log.file=b.log`, I see content in the log file. Could you provide an example app that reproduces this issue?

**Comment by safris** [comment] 2019-12-10 14:06
Hi @haf-tech, I thought deeper about this issue, and believe what's happening is due to a difference in the current working directory of where your app is launched vs where SpecialAgent is launched. I didn't think of this before, and realized there is definitely this issue -- you're providing the path of the file to SpecialAgent, which is being launched in a different directory than the app, but it is the app that is to do the logging. I've made a change that attempts to address this issue. When [this build](https://travis-ci.org/opentracing-contrib/java-specialagent/builds/623192742) completes, please [download the development build](https://github.com/opentracing-contrib/java-specialagent/#2112-development) and try your test again.

**Comment by haf-tech** [comment] 2019-12-10 21:02
Thanks @safris 
 I tested `opentracing-specialagent-1.5.3-20191209.144139-17.jar`; similar behavior. I tried a relative path (a.log) and an absolute one (/tmp/a.log). Log file is still empty.
So the log file will be created, but without any content

would you say this is different in static attachment?

**Comment by haf-tech** [comment] 2019-12-10 21:26
So, I tried static attachment, with similar props:
`-javaagent:/opt/agent/opentracing-specialagent-1.5.3-SNAPSHOT.jar -Dsa.log.level=FINEST -Dsa.log.events=COMPLETE -Dsa.log.file=otagent1.log -Dsa.instrumentation.plugin.verbose=true -Dsa.fingerprint.skip=true`

Result in the log file is now
```
Agent#initialize() java.class.path:
  /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/properties
  /opt/IBM/WebSphere/AppServer/properties
  /opt/IBM/WebSphere/AppServer/lib/startup.jar
  /opt/IBM/WebSphere/AppServer/lib/bootstrap.jar
  /opt/IBM/WebSphere/AppServer/lib/jsf-nls.jar
  /opt/IBM/WebSphere/AppServer/lib/lmproxy.jar
  /opt/IBM/WebSphere/AppServer/lib/urlprotocols.jar
  /opt/IBM/WebSphere/AppServer/deploytool/itp/batchboot.jar
  /opt/IBM/WebSphere/AppServer/deploytool/itp/batch2.jar
  /opt/IBM/WebSphere/AppServer/java/lib/tools.jar
  /opt/agent/opentracing-specialagent-1.5.3-SNAPSHOT.jar
  /opt/agent/opentracing-specialagent-1.5.3-SNAPSHOT.jar
Terminating SpecialAgent due to:
java.lang.StringIndexOutOfBoundsException
        at java.lang.String.substring(String.java:1402)
        at io.opentracing.contrib.specialagent.SpecialAgent.initialize(SpecialAgent.java:196)
        at io.opentracing.contrib.specialagent.Manager.premain(Manager.java:75)
        at io.opentracing.contrib.specialagent.SpecialAgent.premain(SpecialAgent.java:137)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:408)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:423)
```

the current code does not match the line L196. Maybe a property is missing or wrong?

**Comment by safris** [comment] 2019-12-11 12:36
Hi @haf-tech, your use of the "verbose" property is incorrect. Please refer to the directions [here](https://github.com/opentracing-contrib/java-specialagent/#32-properties) for proper usage. Nevertheless, incorrect use of a property should not result in an exception. I will fix this.

**Comment by safris** [comment] 2019-12-11 14:05
Hi @haf-tech, I have implemented changes that attempt to fix the logging issue you are experiencing. When [this build](https://travis-ci.org/opentracing-contrib/java-specialagent/builds/623656215) completes, please [download the development build](https://github.com/opentracing-contrib/java-specialagent/#2112-development) and try your test again.

**Comment by safris** [comment] 2019-12-12 16:16
Hi @haf-tech, we will be releasing SpecialAgent v1.5.3 tomorrow. Can you please confirm whether my latest changes have fixed your issue?

**Comment by haf-tech** [comment] 2019-12-15 09:08
@safris sorry for the belated response. v1.5.3 looks much better with dynamic attachment 

I see some error/exceptions, but I would create therefor a new ticket.
Thanks!

**Closed** 2019-12-15 09:08 UTC
Labels: bug
