### ISSUE TITLE
ClassNotFoundException on Elasticsearch6RestAgentRule

### ISSUE THREAD

**Issue by ledor473** [opentracing-contrib/java-specialagent#56] opened 2019-04-24 20:41 UTC
Using SpecialAgent version 1.1.0, I get the following exception that prevents the application from booting:
```
java.lang.ClassNotFoundException: io.opentracing.contrib.specialagent.elasticsearch.Elasticsearch6RestAgentRule
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:180)
	at <truncated>.EsClientFactory.getClient(EsClientFactory.java:26)
```

**Comment by SevaSafris** [comment] 2019-04-25 08:21
Hi @ledor473, can you provide any insight into your use-case so that I can reproduce this error?

**Comment by ledor473** [comment] 2019-04-25 14:10
@SevaSafris I was able to reproduce that problem with the following steps (#1 is obviously not required if you already have a Spring project)
1. Create an application here: https://start.spring.io/
  - I choose `Java`, `Maven`, `Spring Boot 2.2.0.M2` and no extra deps
2. Add the following dependancies:
```xml
    <dependency>
      <groupId>org.elasticsearch</groupId>
      <artifactId>elasticsearch</artifactId>
      <version>6.3.2</version>
    </dependency>
    <dependency>
      <groupId>org.elasticsearch.client</groupId>
      <artifactId>elasticsearch-rest-client</artifactId>
      <version>6.3.2</version>
    </dependency>
    <dependency>
      <groupId>org.elasticsearch.client</groupId>
      <artifactId>elasticsearch-rest-high-level-client</artifactId>
      <version>6.3.2</version>
    </dependency>
```
3. Add the following class:
```java
package <your package here>

import org.apache.http.HttpHost;
import org.elasticsearch.client.RestClient;
import org.elasticsearch.client.RestClientBuilder;
import org.springframework.context.annotation.Bean;

public class EsConfig {

  @Bean
  public RestClient client() {
    RestClientBuilder builder = RestClient.builder(new HttpHost[]{HttpHost.create("localhost")});
    return builder.build();
  }

}
```

Now if you run that application with the Java Agent you will see the same stack trace.

**Comment by ledor473** [comment] 2019-04-25 14:40
I get similar result with this:
```java 
  @Bean
  public RestHighLevelClient client() {
    RestHighLevelClient client = new RestHighLevelClient(
        RestClient.builder(
            new HttpHost("localhost", 9200, "http"),
            new HttpHost("localhost", 9201, "http")));
    return client;
  }
```

**Comment by malafeev** [comment] 2019-04-26 04:06
@SevaSafris I reproduced the issue: https://github.com/malafeev/sa-apps/tree/master/spring-boot-elasticsearch

**Comment by SevaSafris** [comment] 2019-04-30 16:13
Hi @ledor473, I used the test app that @malafeev made to diagnose this issue. I have pushed a fix for the error produced in the test application, and it is now available in 1.1.1-SNAPSHOT. Would you be able to run your test case against this newest snapshot? Please let me know!

**Comment by ledor473** [comment] 2019-04-30 19:00
@SevaSafris so I pulled the latest using this URL from the README: 
https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=io.opentracing.contrib.specialagent&a=opentracing-specialagent&v=LATEST
Which gave me `opentracing-specialagent-1.1.1-20190430.153439-21.jar`

But when I ran the application with that Java Agent I get:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoClassDefFoundError: io/opentracing/contrib/specialagent/BootLoaderAgent$FindBootstrapResources
	at java.lang.ClassLoader.getBootstrapResources(ClassLoader.java:1276)
	at java.lang.ClassLoader.getResources(ClassLoader.java:1140)
	at java.lang.ClassLoader.getResources(ClassLoader.java:1138)
	at io.opentracing.contrib.specialagent.SpecialAgentUtil.findJarResources(SpecialAgentUtil.java:520)
	at io.opentracing.contrib.specialagent.SpecialAgent.initialize(SpecialAgent.java:196)
	at io.opentracing.contrib.specialagent.ByteBuddyManager.premain(ByteBuddyManager.java:98)
	at io.opentracing.contrib.specialagent.SpecialAgent.premain(SpecialAgent.java:165)
	... 6 more
```

It feels like a packaging issue, so I went ahead and packaged an Agent from master directly and it seems to be working as expected :)

Do you want me to file a bug about the packaging problem of a snapshot release?

**Comment by SevaSafris** [comment] 2019-05-01 11:17
Hi @ledor473, yes please file a new issue for the packaging bug you encountered. I really don't know what could be causing this, and I made sure to check the [snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/io/opentracing/contrib/specialagent/opentracing-specialagent/1.1.1-SNAPSHOT/) directly to make sure you got the correct version, which you did. So, it should have worked for you without having to pull and rebuild yourself.

I'll close this issue now, and if you could, please file the packaging bug.

Thanks for your time helping us make this a better project!

**Closed by SevaSafris** 2019-05-01 11:17 UTC

**Comment by kaushikdeb** [comment] 2019-05-02 13:10
> @SevaSafris so I pulled the latest using this URL from the README:
> https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=io.opentracing.contrib.specialagent&a=opentracing-specialagent&v=LATEST
> Which gave me `opentracing-specialagent-1.1.1-20190430.153439-21.jar`
> 
> But when I ran the application with that Java Agent I get:
> 
> ```
> Exception in thread "main" java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
> 	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
> Caused by: java.lang.NoClassDefFoundError: io/opentracing/contrib/specialagent/BootLoaderAgent$FindBootstrapResources
> 	at java.lang.ClassLoader.getBootstrapResources(ClassLoader.java:1276)
> 	at java.lang.ClassLoader.getResources(ClassLoader.java:1140)
> 	at java.lang.ClassLoader.getResources(ClassLoader.java:1138)
> 	at io.opentracing.contrib.specialagent.SpecialAgentUtil.findJarResources(SpecialAgentUtil.java:520)
> 	at io.opentracing.contrib.specialagent.SpecialAgent.initialize(SpecialAgent.java:196)
> 	at io.opentracing.contrib.specialagent.ByteBuddyManager.premain(ByteBuddyManager.java:98)
> 	at io.opentracing.contrib.specialagent.SpecialAgent.premain(SpecialAgent.java:165)
> 	... 6 more
> ```
> 
> It feels like a packaging issue, so I went ahead and packaged an Agent from master directly and it seems to be **working as expected**  (the application does not crash on boot)
> 
> Do you want me to file a **new issue** about the packaging problem of a snapshot release?

Could someone please explain what assembly fix did make it work for you?
I am getting a java.lang.ClassNotFoundException: io.opentracing.contrib.specialagent.webservletfilter.JettyAgentRule as well and am not sure how to fix it.
Before this exception I was getting: java.lang.NoClassDefFoundError: io/opentracing/contrib/specialagent/BootLoaderAgent$FindBootstrapResources. Renaming the -LATEST.jr to -1.1.1.jar made it progress to the JettyAgentRule NoClassDefFoundError.

**Comment by SevaSafris** [comment] 2019-05-02 14:23
@kaushikdeb, thank you for your comment. You may have actually helped me figure out exactly why this error is happening. Can you rename your JAR to: `opentracing-specialagent-1.1.1-SNAPSHOT.jar` and try again? Please let me know your results!

**Comment by ledor473** [comment] 2019-05-02 15:07
@SevaSafris seems like yoy found the fix! The same Agent I downloaded a few days ago is working if I rename it to `opentracing-specialagent-1.1.1-SNAPSHOT.jar` 👍

**Comment by kaushikdeb** [comment] 2019-05-02 18:34
> @kaushikdeb, thank you for your comment. You may have actually helped me figure out exactly why this error is happening. Can you rename your JAR to: `opentracing-specialagent-1.1.1-SNAPSHOT.jar` and try again? Please let me know your results!

After renaming, it does move pass the previous issue. Now it goes ahead to the next NoClassDefFoundError. Does it have anything to do with the Jetty version that my app is using?

    java.lang.NoClassDefFoundError: org/eclipse/jetty/http/HttpMethod

Any ideas?

**Comment by ledor473** [comment] 2019-05-02 19:09
@kaushikdeb I think this is a different bug. It would be ideal to create a new issue with the full stacktrace and some information about your project (deps version, etc.)

**Comment by SevaSafris** [comment] 2019-05-03 14:47
@kaushikdeb, please create a new issue for the `NoClassDefFoundError`, and provide as much information as possible for debugging.

**Comment by mtrejo** [comment] 2019-05-03 18:39
> Hi @ledor473, I used the test app that @malafeev made to diagnose this issue. I have pushed a fix for the error produced in the test application, and it is now available in 1.1.1-SNAPSHOT. Would you be able to run your test case against this newest snapshot? Please let me know!

@SevaSafris do you have the link to the commit? I'm having a similar issue with a rule I'm creating.

**Comment by SevaSafris** [comment] 2019-05-04 20:13
@mtrejo, the PR that I was referring to is [this one](https://github.com/opentracing-contrib/java-specialagent/commit/5ec30bd920ed0750305ff49db3e7dda5cae4bd59). However, I'm not sure it will help you to look at the diff to understand anything from it. What "similar issue" are you referring to, specifically?

**Comment by mtrejo** [comment] 2019-05-06 23:23
Thanks @SevaSafris, all I needed was use version 1.1.1, the issue is gone now. I was using version 1.1.0.

**Comment by khiradeshubham** [comment] 2019-06-12 09:12
Hello, I am also getting a similar error when I'm dynamically Attaching _specialagent_ to my application

here is what I got in application logs
> java.lang.reflect.InvocationTargetException failed to start!
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)
Caused by: java.lang.IllegalStateException: java.util.zip.ZipException: error in opening zip file
        at io.opentracing.contrib.specialagent.SpecialAgentUtil.findJarResources(SpecialAgentUtil.java:337)
        at io.opentracing.contrib.specialagent.SpecialAgent.initialize(SpecialAgent.java:213)
        at io.opentracing.contrib.specialagent.ByteBuddyManager.premain(ByteBuddyManager.java:102)
        at io.opentracing.contrib.specialagent.SpecialAgent.premain(SpecialAgent.java:165)
        at io.opentracing.contrib.specialagent.SpecialAgent.agentmain(SpecialAgent.java:176)
        ... 6 more
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at io.opentracing.contrib.specialagent.SpecialAgentUtil$Plugin.getPlugin(SpecialAgentUtil.java:348)
        at io.opentracing.contrib.specialagent.SpecialAgentUtil$Plugin.access$000(SpecialAgentUtil.java:341)
        at io.opentracing.contrib.specialagent.SpecialAgentUtil.findJarResources(SpecialAgentUtil.java:292)
        ... 10 more

and this with dynamic attachment,  

> Exception in thread "main" com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
> 	at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
> 	at io.opentracing.contrib.specialagent.SpecialAgent.main(SpecialAgent.java:148)

sorry for spamming

**Comment by malafeev** [comment] 2019-06-12 09:19
@khiradeshubham I think it's better to track in separate issue. Please provide also java version, like output from `java -version` and sample application if possible.

**Comment by khiradeshubham** [comment] 2019-06-13 04:18
@malafeev created one https://github.com/opentracing-contrib/java-specialagent/issues/99
thanks
